---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: tomcat6-package
  run_list: [
    "recipe[tomcat]",
    "recipe[minitest-handler]"
  ]
  attributes: {
    tomcat: {
      install_source: 'package',
      base_version: 6,
      full_version: '6.0.37'
    }
  }

- name: tomcat7-package
  run_list: [
    "recipe[tomcat]",
    "recipe[minitest-handler]"
  ]
  excludes: ["ubuntu-10.04", "centos-6.4"]
  attributes: {
    tomcat: {
      install_source: 'package',
      base_version: 7,
      full_version: '7.0.42'
    }
  }

- name: tomcat6-binary
  run_list: [
    "recipe[tomcat]",
    "recipe[minitest-handler]"
  ]
  attributes: {
    tomcat: {
      install_source: 'binary',
      base_version: 6,
      full_version: '6.0.37'
    }
  }

- name: tomcat7-binary
  run_list: [
    "recipe[tomcat]",
    "recipe[minitest-handler]"
  ]
  attributes: {
    tomcat: {
      install_source: 'binary',
      base_version: 7,
      full_version: '7.0.42'
    }
  }
